on: [push]

jobs:
  jekyll_job:
    runs-on: ubuntu-latest
    name: Generate static site
    steps:
    - uses: actions/checkout@v1
    - name: Building the site
      id: jekyll_build
      uses: phuang07/gh-actions@master
      with:
        jekyll_version: '3.8.5'
        cname: 'gh-action.phuang07.github.io'
    # Use the output from the `hello` step
    # - name: Get the output time
    #   run: echo "The time was ${{ steps.hello.outputs.time }}"
